### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by vbauerster** [sawdust-and-diamonds/scrollbar.kak#8]
I installed the plugin and compiled binary like `make kak-calc-scrollbar`.
Then manually issuing `:scrollbar-enable` does nothing, I mean there is no any visible scroll bar I can see.

Manually invoking the binary results in the following error:
```
bash-5.1$ ./kak-calc-scrollbar
Segmentation fault: 11
```

Is it problem with binary or did I miss something?

**Comment by vbauerster** [comment]
I put some debug on line 33:
![Screen Shot 2021-06-20 at 22 45 25](https://user-images.githubusercontent.com/2206533/122683610-cec58a80-d219-11eb-8525-8094aa0c6671.png)

I believe binary is invoked with params like in debug window above, but such call produce same Segmentation fault error:
```
❯ /Users/vbauer/.config/kak/plugins/github.com/sawdust-and-diamonds/scrollbar.kak/kak-calc-scrollbar 11 44 29.18,29.20 28.18,28.20 ▓ █ 74 33
zsh: segmentation fault   11 44 29.18,29.20 28.18,28.20 ▓ █ 74 33
```

**Comment by Screwtapello** [comment]
Can you recompile the tool with `-fsanitize=address`, rerun the command that segfaults, then paste the output here?

Are you using an Intel-based or an ARM-based Mac?

**Comment by vbauerster** [comment]
I use intel based mac.

Running with some params

```
=================================================================
==63161==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000000ff at pc 0x00010bdfae00 bp 0x7ffee3e3c430 sp 0x7ffee3e3bbc8
WRITE of size 16 at 0x6020000000ff thread T0
    #0 0x10bdfadff in wrap_vsprintf+0x1bf (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x23dff)
    #1 0x10bdfb46c in wrap_sprintf+0xac (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x2446c)
    #2 0x10bdc4f5a in append_char+0xaa (a.out:x86_64+0x100002f5a)
    #3 0x10bdc548f in main+0x51f (a.out:x86_64+0x10000348f)
    #4 0x7fff205b4f5c in start+0x0 (libdyld.dylib:x86_64+0x15f5c)

0x6020000000ff is located 0 bytes to the right of 15-byte region [0x6020000000f0,0x6020000000ff)
allocated by thread T0 here:
    #0 0x10be1f4c0 in wrap_malloc+0xa0 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x484c0)
    #1 0x10bdc4ed6 in append_char+0x26 (a.out:x86_64+0x100002ed6)
    #2 0x10bdc548f in main+0x51f (a.out:x86_64+0x10000348f)
    #3 0x7fff205b4f5c in start+0x0 (libdyld.dylib:x86_64+0x15f5c)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x23dff) in wrap_vsprintf+0x1bf
Shadow bytes around the buggy address:
  0x1c03ffffffc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03ffffffd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03ffffffe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03fffffff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c0400000000: fa fa fd fd fa fa 00 00 fa fa 00 06 fa fa 00 fa
=>0x1c0400000010: fa fa 00 04 fa fa 00 00 fa fa 00 06 fa fa 00[07]
  0x1c0400000020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==63161==ABORTING
zsh: abort       11 44 29.18,29.20 28.18,28.20 a b 74 33
```

Running without params
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==65651==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fff204ceb96 bp 0x7ffee700d560 sp 0x7ffee700d530 T0)
==65651==The signal is caused by a READ memory access.
==65651==Hint: address points to the zero page.
    #0 0x7fff204ceb96 in strtol_l+0x4d (libsystem_c.dylib:x86_64+0x60b96)
    #1 0x108c46e29 in wrap_strtol+0x59 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x43e29)
    #2 0x108bf3fd3 in main+0x63 (a.out:x86_64+0x100002fd3)
    #3 0x7fff205b4f5c in start+0x0 (libdyld.dylib:x86_64+0x15f5c)

==65651==Register values:
rax = 0x00007fff872a68c0  rbx = 0x0000000000000000  rcx = 0x00007fff808907a0  rdx = 0x000000000000000a
rdi = 0x0000000000000000  rsi = 0x00007ffee700d578  rbp = 0x00007ffee700d560  rsp = 0x00007ffee700d530
 r8 = 0x00007fff808907a0   r9 = 0x00007fff808901d8  r10 = 0x00007fff808c5cc0  r11 = 0x00007fff204ced51
r12 = 0x0000000000000000  r13 = 0x0000000000000000  r14 = 0x00007ffee700d578  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_c.dylib:x86_64+0x60b96) in strtol_l+0x4d
==65651==ABORTING
zsh: abort
```

**Comment by Screwtapello** [comment]
In retrospect I should probably have also suggested the code be compiled with `-g -Og` for nice debug symbols, but with code this short it's not difficult to see what's going on: `append_char()` calls `sprintf()`:

https://github.com/sawdust-and-diamonds/scrollbar.kak/blob/main/kak-calc-scrollbar.c#L79-L87

`append_char()` is called to append the selection char (say, `█`) to the format string (say, `{ScrollbarSel}`) to produce a Kakoune line-flag.

The problem is that although the function is called `append_char()`, it takes a `char *` argument, and it allocates `strlen(str)+1` bytes for the new buffer... the second argument isn't actually a single char, it's a multibyte string (`\xE2\x96\x88` assuming UTF-8 encoding) so allocating a single additional byte isn't going to cut it.

This code should be modified to call `strcat()`, or replaced with my AWK rewrite (#5) :)

**Comment by vbauerster** [comment]
I confirm awk fork is working on my side. Hope it's going to be merged soon.

**Comment by sawdust-and-diamonds** [comment]
That's brilliant. I'm sorry for being inactive. Let's do it.
